s = set()
item1 = input("enter item: ")
s.add(int(item1))
item2 = input("enter item: ")
s.add(int(item2))
item3 = input("enter item: ")
s.add(int(item3))
item4 = input("enter item: ")
s.add(int(item4))
item5 = input("enter item: ")
s.add(int(item5))
item6 = input("enter item: ")
s.add(int(item6))
item7 = input("enter item: ")
s.add(int(item7))
item8 = input("enter item: ")
s.add(int(item8))
print(s)